# Site settings
title: YQ Blog
SEOTitle: 勇气的博客 | YQ Blog
header-img: img/post-bg-desk.jpg
email: 1242516962@qq.com
description: "做好招聘，首先要做好猎头"
keyword: "YQ, YQ Blog, 勇气的博客, 勇气"
url: "http://yanyongqi911.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/yanyongqi911/yanyongqi911.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "未来不迎，当下不杂，既过不恋"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    yanyongqi911
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: yanyongqi911

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 459da68d67dd858d1a33                            #生成的clientID
  clientSecret: 663c4743f25a6c688432315bae9ae340998d3882    #生成的clientSecret
  repo: yanyongqi911.github.io    #仓库名称
  owner: yanyongqi911    #github用户名
  admin: yanyongqi911
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "baidu",
        href: "http://baidu.com"
    },{
        title: "google",
        href: "http://www.google.com"
    },{
        title: "Apple",
        href: "https://apple.com"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]

theme: jekyll-theme-cayman
